import type { ChatCompletionMessageToolCall } from './chat-completion-assistant-message-params.js';
import type { ZhipuAIFinishReason } from './chat-completion-choice.js';

export interface ChatCompletionChunkChoiceDelta {
  content?: string | null;

  // role?: 'system' | 'user' | 'assistant' | 'tool';
  role?: 'assistant';

  tool_calls?: Array<ChatCompletionMessageToolCall>;
}

export interface ChatCompletionChunkChoice {
  /**
   * A chat completion delta generated by streamed model responses.
   */
  delta: ChatCompletionChunkChoiceDelta;

  /**
   * - stop: if the model hit a natural stop point or a provided stop sequence
   * - length: if the maximum number of tokens specified in the request was reached
   * - content_filter: if content was omitted due to a flag from our content filters
   * - tool_calls: if the model called a tool
   * - @zhipuai sensitive: if the model detected sensitive content
   * - @zhipuai network_error: if the model encountered a network error
   */
  finish_reason: ('stop' | 'length' | 'tool_calls' | 'content_filter') &
    ZhipuAIFinishReason;

  index: number;

  /**
   * Log probability information for the choice.
   */
  // logprobs?: Choice.Logprobs | null;
}
